title: mcautograder Documentation
author: Chris Pyles
description: documentation for Python package mcautograder
navigation:
  nav_title: Contents
  links:
    - title: Home
      url: index.html
    - title: Usage
      url: usage.html
    - title: Tests
      url: tests.html
    - title: Docs
      url: docs.html
    - title: License
      url: license.html
